//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementSystemWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendorCreation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVendorCreation()
        {
            this.tblAssetMasters = new HashSet<tblAssetMaster>();
            this.tblPurchaseOrders = new HashSet<tblPurchaseOrder>();
        }
    
        public decimal vd_id { get; set; }
        public string vd_name { get; set; }
        public string vd_type { get; set; }
        public Nullable<decimal> vd_type_id { get; set; }
        public System.DateTime vd_from { get; set; }
		public string vFrom 
		{
			get {
				return vd_from.ToString("yyyy-MM-dd");
				}
	    }
		public System.DateTime vd_to { get; set; }
		public string vTo 
        { 
           get {return vd_to.ToString("yyyy-MM-dd");
			} 
         }
		public string vd_addr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssetMaster> tblAssetMasters { get; set; }
        public virtual tblAssetType tblAssetType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrder> tblPurchaseOrders { get; set; }
    }
}
